# Generated by Django 5.2.6 on 2025-09-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('STUDIO', 'Studio Apartment'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('4BR', '4 Bedroom Apartment'), ('SHOP', 'Mall Shop')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('initial_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('installment_plan', models.CharField(blank=True, max_length=200)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('parking', models.PositiveIntegerField(default=0)),
                ('square_meters', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('gallery1', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('gallery2', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.property')),
            ],
        ),
    ]
