# Generated by Django 5.2.7 on 2025-10-05 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('STUDIO', 'Studio Apartment'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('FARM', 'Farm Land'), ('LAND', 'Land Asset'), ('SHOP', 'Mall Shop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='UnitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('STUDIO', 'Studio Apartment'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('FARM', 'Farm Land'), ('LAND', 'Land Asset'), ('SHOP', 'Mall Shop')], max_length=10)),
                ('label', models.CharField(blank=True, help_text="Optional display label, e.g. '2-Bedroom + BQ'", max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('initial_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plan_0_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plan_3_6', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plan_6_12', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='listings.property')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.unitoption'),
        ),
    ]
