# Generated by Django 5.2.7 on 2025-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_property_category_alter_property_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('STUDIO', 'Studio Apartment'), ('RESIDENT', 'Residential'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('4BR', '3 Bedroom Apartment'), ('FARM', 'Farm Land'), ('LAND', 'Land Asset'), ('SHOP', 'Mall Shop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='unitoption',
            name='unit_type',
            field=models.CharField(choices=[('STUDIO', 'Studio Apartment'), ('RESIDENT', 'Residential'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('4BR', '3 Bedroom Apartment'), ('FARM', 'Farm Land'), ('LAND', 'Land Asset'), ('SHOP', 'Mall Shop')], max_length=10),
        ),
    ]
